### ISSUE TITLE
Production readiness?

### ISSUE THREAD

**Issue by tmm1** [djherbis/bufit#1]
I noticed this project hasn't received any commits in a while.. is that because it's stable and works, or because it's not being actively used anywhere?

It seems like it would work really well for my use-case, so I'm trying to get a sense of what to expect before I try to replace what I'm currently using.

The only feature that I didn't see built-in is the ability to bound the size of the memory buffer. But it seems like that would be pretty straightforward to implement in a wrapper, by looking at the `Len()` of the buffer after every write, and calling `Discard()` to drop the oldest bytes once the length grows beyond the limit.

**Comment by djherbis** [comment]
I try to be strict about respecting my semvar versions, so when I went 1.0 I guaranteed API stability.

That being said, the only true way to be 'production ready' imho is to have used it in more 'real circumstances' (not just my unit tests), to which, I haven't used it that heavily yet.

While I haven't committed in awhile, I don't plan to abandon this project. I'd like to add more buffering strategies like how buffer and nio interact (though I can't integrate this library with them do to some behavioral differences). 

A custom Writer implementation would be needed to support other buffering strategies. The bufit.Buffer type is actually not intended to implement the Writer interface, it's supposed to accept something which implements the bufit.Writer interface and then it adds all the signaling and reader/buffer management on top of the Writer itself. Whereas the bufit.Writer is intended to just manage a shared buffer with no signaling or reader/writer management.

I'll talk about how we can write a custom bufit.Writer in your pull request.

**Comment by djherbis** [comment]
After reviewing the code a bit, I think I'm going to have to modify Buffer to allow for bounding the size of the buffer, the locking makes it difficult to do without double-locking otherwise.

**Comment by tmm1** [comment]
I think it's safe to say that this library is production-ready. I found some minor bugs when I switched over, but they've all been fixed on master.

There is also a Capped implementation on master now, which addresses my concerns about unbounded resource usage.

**Comment by tmm1** [comment]
@djherbis What's the best way to print out a warning when the cap is triggered?

**Comment by djherbis** [comment]
The easiest way is probably just to call buf.Len() before/after each write and see how close it is to the cap.

You could keep some stats on the length of the buffer, if you notice it's often close to the cap, then you might consider increasing the cap.

**Comment by tmm1** [comment]
Thanks! I ended up checking Len() before the Write, to print out warnings once it gets over 50%, 75% and 95% of the cap. I can monitor logs for the next week and adjust the size of the cap accordingly.

**Comment by djherbis** [comment]
Sounds good, have you tried any metric libraries? In a past life I used statsd to track things like the size of buffers, then I could add monitoring and alerting as required. Also made it easier to visualize buffer growth over time etc.
