### ISSUE TITLE
Runtime panic

### ISSUE THREAD

**Issue by tmm1** [djherbis/bufit#5]
Saw this earlier:

```
panic: runtime error: index out of range

goroutine 102 [running]:
github.com/tmm1/bufit.(*readerHeap).Swap(0xc4205d4568, 0x1, 0x0)
        <autogenerated>:8 +0x10c
container/heap.Remove(0x4a90580, 0xc4205d4568, 0x1, 0x405f335, 0xc420973310)
        /usr/local/Cellar/go/1.8/libexec/src/container/heap/heap.go:74 +0x9c
github.com/tmm1/bufit.(*Buffer).drop(0xc4205d4540, 0xc420973340)
        go/src/github.com/tmm1/bufit/bufit.go:100 +0x85
github.com/tmm1/bufit.(*reader).Close(0xc420973340, 0xc420887600, 0x47a0570)
        go/src/github.com/tmm1/bufit/heap.go:66 +0x5c
```

Possibly fixed already when we added locking to `Close()` earlier tonight?

**Comment by tmm1** [comment]
Actually it looks like I was running a build that contained that commit already. Specifically https://github.com/tmm1/bufit/commit/c551e8f90d2d82be5c7288931695c3b25e67814b from https://github.com/tmm1/bufit/commits/mine

**Comment by djherbis** [comment]
Hmm, this is the reader close not the buffer close so it's a separate issue.

**Comment by djherbis** [comment]
I'm taking a look.

**Comment by djherbis** [comment]
Is it possible that you called Close() twice on a reader?

**Comment by djherbis** [comment]
I was able to replicate this by calling close on the reader twice (it looks to me like the only way this is possible).

I've made the reader.Close call idempotent so that should fix it (added a test case to catch it too).

**Comment by tmm1** [comment]
Thanks, that's probably what happened. I saw it a few more times tonight, so I should be able to reproduce and confirm in the morning.

**Comment by djherbis** [comment]
Thanks for testing it out!

**Comment by tmm1** [comment]
It would be nice if `Close()` returned an error if you tried to call it twice. In my case I want to close the Buffer when the last reader closes, which is tricky to do when you can't tell if the reader was closed already or not.

Looks like there's no easy way to do this with `sync.Once` though..

**Comment by tmm1** [comment]
Hmm, `*os.File` returns "invalid argument" if you close it a second time but `*io.PipeReader` does not. Perhaps its best if I don't rely on the return value of `Close()`

**Comment by djherbis** [comment]
How are you detecting that all the readers have closed?
We could expose the length of the readerHeap on the buffer, this would tell you how many open readers were on the buffer.

**Comment by djherbis** [comment]
It is possible for the Close to return an error on a second close, but I'm not sure if we should do that or not.

```go
// This will return true after the first call.
var once sync.Once
alreadyDone := true
once.Do(func(){
  alreadyDone = false
})
return alreadyDone
```

**Comment by tmm1** [comment]
> How are you detecting that all the readers have closed?
> We could expose the length of the readerHeap on the buffer, this would tell you how many open readers were on the buffer.

I had to wrap both the buffer and reader to keep a refcount.

Exposing the length would definitely make it easier. I also wonder if this is a useful enough feature to be added to the library, something like `buf.CloseAfterLastReader = true`

**Comment by djherbis** [comment]
I'm curious why you need to close the buffer when all the readers drop off instead of when its done consuming data. Usually you would close the buffer once all the data you intend to write is written and that tells the readers that there will be no more data.

I think it's less common to stop the writer when the 'last' reader drops off. Especially since new readers could join later.

**Comment by tmm1** [comment]
The stream in my case is a live video feed, so there's never an end to the incoming data. I have different types of consumers in my application (that either store, process or proxy the stream), and I'm using the shared buffer to optimize for the case where multiple consumers are active at the same time.

**Comment by djherbis** [comment]
Ah I see that seems like a reasonable use case for wanting it to only exist as long as there are consumers.

Do you mind opening up a new issue as a feature request (since this one is a bug). 
Then we can discuss the expected behavior/api there.

Also, can I mark this bug closed? Has it happened again since the fix?

**Comment by tmm1** [comment]
Panic has not occurred again, so this bug is fixed!
