### ISSUE TITLE
Auto-close Buffer after last reader closes

### ISSUE THREAD

**Issue by tmm1** [djherbis/bufit#6]
`bufit` is useful when multiple consumers need to work off a live stream of data. In this use-case, a Buffer is created on-demand when a consumer tunes in, and can be re-used if other consumers are interested in concurrent access.

When the last reader disconnects, it would be useful to be able to tell the Buffer to automatically close itself.

**Comment by djherbis** [comment]
I'm just going over a few different ways to configure this behavior which allows for flexibility, consistency and compatibility with the existing api.

**Comment by djherbis** [comment]
The latest commit provides this feature:

```go
buf := bufit.New()

// call close when last reader drops off
buf.OnLastReaderClose(buf.Close)

// or if you need need to do more work:
buf.OnLastReaderClose(func() error {
  // do other work, probably unregister the buffer so NextReader() isn't called anymore
  return buf.Close()
})
```

Currently the callbacks error is ignored, but it's included in the signature since Close() returns an error.

**Comment by tmm1** [comment]
Very nice API! Can't wait to try it out.

**Comment by tmm1** [comment]
The new API worked out wonderfully. I was able to get rid of a bunch of code in my app by switching over to it.
